# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import permissions.models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_auto_20140830_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpermission',
            name='access_project',
            field=permissions.models.ProjectPermissionField(default=False),
        ),
        migrations.AlterField(
            model_name='globalpermission',
            name='create_comment',
            field=permissions.models.ProjectPermissionField(default=False),
        ),
        migrations.AlterField(
            model_name='globalpermission',
            name='create_issue',
            field=permissions.models.ProjectPermissionField(default=False),
        ),
        migrations.AlterField(
            model_name='globalpermission',
            name='create_project',
            field=permissions.models.GlobalPermissionField(default=True, verbose_name='Create project'),
        ),
        migrations.AlterField(
            model_name='globalpermission',
            name='delete_comment',
            field=permissions.models.ProjectPermissionField(default=False),
        ),
        migrations.AlterField(
            model_name='globalpermission',
            name='delete_issue',
            field=permissions.models.ProjectPermissionField(default=False),
        ),
        migrations.AlterField(
            model_name='globalpermission',
            name='delete_project',
            field=permissions.models.GlobalPermissionField(default=False),
        ),
        migrations.AlterField(
            model_name='globalpermission',
            name='delete_tags',
            field=permissions.models.ProjectPermissionField(default=False),
        ),
        migrations.AlterField(
            model_name='globalpermission',
            name='manage_accounts',
            field=permissions.models.GlobalPermissionField(default=False),
        ),
        migrations.AlterField(
            model_name='globalpermission',
            name='manage_global_permission',
            field=permissions.models.GlobalPermissionField(default=False),
        ),
        migrations.AlterField(
            model_name='globalpermission',
            name='manage_issue',
            field=permissions.models.ProjectPermissionField(default=False),
        ),
        migrations.AlterField(
            model_name='globalpermission',
            name='manage_project_permission',
            field=permissions.models.ProjectPermissionField(default=False),
        ),
        migrations.AlterField(
            model_name='globalpermission',
            name='manage_settings',
            field=permissions.models.GlobalPermissionField(default=False),
        ),
        migrations.AlterField(
            model_name='globalpermission',
            name='manage_tags',
            field=permissions.models.ProjectPermissionField(default=False),
        ),
        migrations.AlterField(
            model_name='globalpermission',
            name='modify_comment',
            field=permissions.models.ProjectPermissionField(default=False),
        ),
        migrations.AlterField(
            model_name='globalpermission',
            name='modify_issue',
            field=permissions.models.ProjectPermissionField(default=False),
        ),
        migrations.AlterField(
            model_name='globalpermission',
            name='modify_project',
            field=permissions.models.GlobalPermissionField(default=False),
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='create_comment',
            field=permissions.models.PermissionField(default=True),
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='create_issue',
            field=permissions.models.PermissionField(default=True),
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='delete_comment',
            field=permissions.models.PermissionField(default=False),
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='delete_issue',
            field=permissions.models.PermissionField(default=False),
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='delete_tags',
            field=permissions.models.PermissionField(default=False),
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='manage_issue',
            field=permissions.models.PermissionField(default=False),
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='manage_project_permission',
            field=permissions.models.PermissionField(default=False),
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='manage_tags',
            field=permissions.models.PermissionField(default=False),
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='modify_comment',
            field=permissions.models.PermissionField(default=False),
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='modify_issue',
            field=permissions.models.PermissionField(default=False),
        ),
    ]
