# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 12:27
from __future__ import unicode_literals

from django.db import migrations
import permissions.models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0007_auto_20140905_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpermission',
            name='modify_own_comment',
            field=permissions.models.ProjectPermissionField(default=False, verbose_name='Modify his issue and comment'),
        ),
        migrations.AddField(
            model_name='projectpermission',
            name='modify_own_comment',
            field=permissions.models.PermissionField(default=False, verbose_name='Modify his issue and comment'),
        ),
    ]
