# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-26 08:15
from __future__ import unicode_literals

from django.db import migrations
import permissions.models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0007_auto_20140905_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpermission',
            name='modify_his_comment',
            field=permissions.models.PermissionField(default=False, verbose_name='Modify his comment'),
        ),
    ]
