# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-26 11:45
from __future__ import unicode_literals

from django.db import migrations
import permissions.models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0008_projectpermission_modify_his_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpermission',
            name='modify_his_comment',
            field=permissions.models.ProjectPermissionField(default=False, verbose_name='Modify his comment'),
        ),
    ]
