# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 09:03
from __future__ import unicode_literals

from django.db import migrations
import permissions.models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0009_globalpermission_modify_his_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalpermission',
            old_name='modify_his_comment',
            new_name='modify_own_comment',
        ),
        migrations.RenameField(
            model_name='projectpermission',
            old_name='modify_his_comment',
            new_name='modify_own_comment',
        ),
        migrations.AlterField(
            model_name='globalpermission',
            name='modify_own_comment',
            field=permissions.models.ProjectPermissionField(default=False, verbose_name='Modify his issue and comment'),
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='modify_own_comment',
            field=permissions.models.PermissionField(default=False, verbose_name='Modify his issue and comment'),
        ),
    ]
