#!/usr/bin/env python

import sys
import requests


if len(sys.argv) != 2:
    print("Usage: %s KEY@URL" % sys.argv[0])
    sys.exit(1)

key, url = sys.argv[1].split('@')

email = sys.stdin.read()
print(email) # DO NOT REMOVE

requests.post(
    url,
    data={
        'key': key,
    },
    files={
        'email': ('email.txt', email),
    }
)
