# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-26 10:10
from __future__ import unicode_literals

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_project_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='edit_policy',
            field=models.IntegerField(choices=[(0, 'No timeout'), (1, 'Timeout'), (2, 'As long no next comment')], default=0, verbose_name='Policy for "Modify his issue and comment" permission'),
        ),
        migrations.AddField(
            model_name='settings',
            name='edit_policy_timeout',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Timeout for "Modify his issue and comment" permission (in min)'),
        ),
        migrations.CreateModel(
            name='ReadState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastread', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readstates', to='tracker.Issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readstates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='readstate',
            unique_together=set([('issue', 'user')]),
        ),
    ]
