# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-26 10:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_project_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='edit_policy',
            field=models.IntegerField(choices=[(0, 'No timeout'), (1, 'Timeout'), (2, 'As long no next comment')], default=0, verbose_name='Policy for "Modify his comment" permission'),
        ),
        migrations.AddField(
            model_name='settings',
            name='edit_policy_timeout',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Timeout for "Modify his comment" permission (in min)'),
        ),
    ]
