# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 09:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20171031_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='edit_policy',
            field=models.IntegerField(choices=[(0, 'No timeout'), (1, 'Timeout'), (2, 'As long no next comment')], default=0, verbose_name='Policy for "Modify his issue and comment" permission'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='edit_policy_timeout',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Timeout for "Modify his issue and comment" permission (in min)'),
        ),
    ]
